### ISSUE TITLE
Request failed status 429

### ISSUE THREAD

**Issue by gastontancredi** [Aldhanekaa/GoogleBardObsidian#3]
Hi,
I I am trying to use this feature after installed and it is not working, I get "Request failed status 429", I followed the steps described,

<img width="920" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/5db99d09-4814-4dfa-9787-862204d904bc">

<img width="733" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/e9a5842c-52e5-4aa9-bf6d-ff638a6b066e">

**Comment by gastontancredi** [comment]
<img width="150" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/1788778a-9c43-46ef-8dc0-f1ea8b1b0e3f">

**Comment by Aldhanekaa** [comment]
What is your Plugin Version? 

If it's matched with latest version, can you try to click `refresh` button, then click `new chat` button?

**Comment by gastontancredi** [comment]
Using this one https://github.com/Aldhanekaa/GoogleBardObsidian/releases/tag/0.3.6
I tried refresh but still, not working, also new conversation does not open a new conversation either. 

<img width="749" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/80b7214e-85da-4cb2-bdf8-500a02c7550f">
<img width="458" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/ed13548e-aa11-4fba-9d65-248f12144ffd">

<img width="156" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/7628b386-cdf7-480a-b474-921bd87190fe">

<img width="134" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/d2149844-2eec-47cc-89ad-9595565d3dbc">

<img width="128" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/6920188d-6bb5-436e-9bde-a91bd32034a5">

**Comment by Aldhanekaa** [comment]
> 

oh you actually need to include the `.` (period).

**Comment by gastontancredi** [comment]
I tried that but did not work
<img width="668" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/ba0d4047-8135-4c2b-97c8-2fbc5b520f01">
<img width="465" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/d2032123-4a8c-4e2a-8797-cbd3d909bf61">
<img width="365" alt="image" src="https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/9bf80beb-c206-4f83-bd09-087e76a7c3e5">

**Comment by danieltomasz** [comment]
@gastontancredi which obsidian version you are in? I am on Obsidian 1.4.1 preview and   plugin ver 3.6 (it was added to Obsidian community store) and it works for me

**Comment by gastontancredi** [comment]
@danieltomasz my version is 1.3.7 in both linux and windows, downloaded from here https://obsidian.md/download 
just updated today to the versions available there and didn´t work

**Comment by gastontancredi** [comment]
Hey I reinstalled from community plugins, now I see it available there, and used default browser and worked on linux (Ubuntu 23.04) https://i.imgur.com/9ocnrQY.png
However on windows, I couldn't make it work yet. Now it doesn't fail, it is "sucessfully loaded" but keeps "thinking"

**Comment by gastontancredi** [comment]
![image](https://github.com/Aldhanekaa/GoogleBardObsidian/assets/67171481/4d1532f8-f538-4db9-b98a-693882d0fef0)

**Comment by Aldhanekaa** [comment]
I'm glad to see it works! Thanks for using the plugin!
 I'm really sorry that I'm unable to reply to you, I have been busy lately.
